services:
  postgres:
    image: postgres:16
    container_name: produit-postgres
    environment:
      POSTGRES_DB: produit_db
      POSTGRES_USER: produit
      POSTGRES_PASSWORD: produit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U produit -d produit_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: produit-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  commande-postgres:
    image: postgres:16
    container_name: commande-postgres
    environment:
      POSTGRES_DB: commande_db
      POSTGRES_USER: commande
      POSTGRES_PASSWORD: commande
    ports:
      - "5433:5432"
    volumes:
      - commande_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commande -d commande_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  commande_postgres_data:
